<?php

/**
 *
 * @file
 * Force Revisions
 *
 * creates a new revision of a node on every save event 
 *
 * inspired by:
 * - https://drupal.stackexchange.com/a/215057
 * - https://drupal.stackexchange.com/a/253555
 *
 */

use Drupal\Core\Entity;
use Drupal\Core\Entity\EntityInterface;

function force_revisions_entity_presave(EntityInterface $entity) {
  if (!in_array($entity->getEntityTypeId(), ['user', 'file']) && method_exists($entity, 'setNewRevision')) {
    $entity->setNewRevision(TRUE);
    $entity->setRevisionUserId(\Drupal::currentUser()->id());
    $entity->setRevisionCreationTime($_SERVER['REQUEST_TIME']);
  }
}
